export {}
const { v4: uuidv4 } = require('uuid');

class Task {
  id: string

  title: string

  order: number

  description: string

  userId: string | null

  boardId: string

  columnId: string

  /**
   * Create a Task
   * 
   * @param {string} id The Task's generated by id (uuidv4())
   * @param {string} title The Task's full title
   * @param {nuber} order The Task's order
   * @param {string} description The Task's description
   * @param {string} userId The Task's userId
   * @param {string} boardId The Task's boardId
   * @param {string} columnId The Task's columnId
   */
  constructor({
    id = uuidv4(),
    title = 'TASK',
    order = 0,
    description = "TASK",
    userId = 'userId',
    boardId = 'boardId',
    columnId = 'columnId'
  } = {}) {
    this.id = id;
    this.title = title;
    this.order = order;
    this.description = description;
    this.userId = userId;
    this.boardId = boardId;
    this.columnId = columnId;
  }

  /**
   * Static method User
   * 
   * @param {Object} task Accept object {{id, title, order, description, userId, boardId, columnId}}
   * @returns {Object} Return object {{id, title, order, description, userId, boardId, columnId}}
   */
  static toResponse(task: Task) {
    const {id, title, order, description, userId, boardId, columnId} = task
    return {id, title, order, description, userId, boardId, columnId}
  }
}
module.exports = Task;
