version: '3.8'

services:
  node:
    build: .
    command: npm run start
    networks:
      - custom-net
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

  postgres:
    build: ./database
    networks:
      - custom-net
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  custom-net:
    driver: bridge

volumes: 
  pgdata: