version: '3.0'

services: 
  node:
    build: .
    ports: 
      - ${PORT}:${PORT}
    command: npm run start
    environment: 
      - PORT=8080
    depends_on: 
      - postgres
    restart: always
  postgres:
    build: ./database/
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
