export {}
const { v4: uuidv4 } = require('uuid');
const Сolumns = require('./column.model.ts')

function createColumn(option: Array<object>) {
  const columns = []
  for(let i=0; i < option.length; i +=1) {
    columns.push(new Сolumns(option[i]))
  }
  return columns
}

class Board {
  id: string

  title: string

  columns: Array<object>

  /**
   * Create a Board
   * @param {string} id The Board's generated by id (uuidv4())
   * @param {string} title The Board's title
   * @param {Array} columns The Board's columns
   */
  constructor({
    id = uuidv4(),
    title = 'BOARD',
    columns = []
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = createColumn(columns)
  }
}

module.exports = Board;
